/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test_prot.h"


void
test_program_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	inputs  execute_primitive_1_arg;
	strcpy(execute_primitive_1_arg.cmd,"RESERVE_SPACE");

#ifndef	DEBUG
	clnt = clnt_create (host, TEST_PROGRAM, TEST_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = execute_primitive_1(&execute_primitive_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("Response:%s\n",(char*)*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	test_program_1 (host);
exit (0);
}
