/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test_prot.h"

#define SPLIT_S_ADDR_INTO_BYTES( \
    s_addr) \
    ((s_addr) >> 24) & 0xFF, \
    ((s_addr) >> 16) & 0xFF, \
    ((s_addr) >>  8) & 0xFF, \
    ((s_addr)      ) & 0xFF


const char *filepath = "client_requests.txt";

int store_data(const char *data, const char* ipaddress)
{
	int ret = 0;
	FILE *fp = fopen(filepath, "a");
	if (fp != NULL)
	{
		fputs(ipaddress, fp);	//return value of fputs can be checked.
		fputs(data, fp);
		fputs("\n",fp);
        	fclose(fp);
		ret = 1;
	}
	return ret;
}

char **
execute_primitive_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static char * result="FAILED";
	//printf("Request from client:%s\n",argp->cmd);
	//printf("client address: %u\n", rqstp->rq_xprt->xp_raddr.sin_addr.s_addr);
	char ipaddress[15];
	sprintf(ipaddress,"[%hu.%hu.%hu.%hu] ", SPLIT_S_ADDR_INTO_BYTES(ntohl(rqstp->rq_xprt->xp_raddr.sin_addr.s_addr)));
	
	printf("Request from client %s: %s\n",ipaddress, argp->cmd);
	
	if (store_data(argp->cmd, ipaddress) == 1)
	{
		result = "SUCCESS";
	}
	return &result;
}
