/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_PROT_H_RPCGEN
#define _TEST_PROT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	char cmd[32];
};
typedef struct inputs inputs;

#define TEST_PROGRAM 1707
#define TEST_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define execute_primitive 1
extern  char ** execute_primitive_1(inputs *, CLIENT *);
extern  char ** execute_primitive_1_svc(inputs *, struct svc_req *);
extern int test_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define execute_primitive 1
extern  char ** execute_primitive_1();
extern  char ** execute_primitive_1_svc();
extern int test_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_PROT_H_RPCGEN */
